name: Yahtzee

on:
  push:
    branches: [main, refactor_pipeline]


jobs:
  Roll-first-die:
    runs-on: ubuntu-latest
    outputs:
      first_die: ${{ steps.Roll_dice.outputs.FIRSTROLL }}
    steps:
    - id: Roll_dice
      run: |
        FIRSTNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=FIRSTROLL::$FIRSTNUM
  Roll-second-die:
    runs-on: ubuntu-latest
    outputs:
      second_die: ${{ steps.Roll_dice.outputs.SECONDROLL }}
    steps:
    - id: Roll_dice
      run: |
        SECONDNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=SECONDROLL::$SECONDNUM
  Roll-third-die:
    runs-on: ubuntu-latest
    outputs:
      third_die: ${{ steps.Roll_dice.outputs.THIRDROLL }}
    steps:
    - id: Roll_dice
      run: |
        THIRDNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=THIRDROLL::$THIRDNUM
  Roll-fourth-die:
    runs-on: ubuntu-latest
    outputs:
      fourth_die: ${{ steps.Roll_dice.outputs.FOURTHROLL }}
    steps:
    - id: Roll_dice
      run: |
        FOURTHNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=FOURTHROLL::$FOURTHNUM
  Roll-fifth-die:
    runs-on: ubuntu-latest
    outputs:
      fifth_die: ${{ steps.Roll_dice.outputs.FIFTHROLL }}
    steps:
    - id: Roll_dice
      run: |
        FIFTHNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=FIFTHROLL::$FIFTHNUM
  Print-First-Roll:
    runs-on: ubuntu-latest
    needs: Roll-dice
    steps:
    - id: print-first-roll
      run:
        echo First roll is ${{needs.Roll-dice.outputs.first_die}}${{needs.Roll-dice.outputs.second_die}}${{needs.Roll-dice.outputs.third_die}}${{needs.Roll-dice.outputs.fourth_die}}${{needs.Roll-dice.outputs.fifth_die}}
