name: Yahtzee

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: Roll first dice
      run: echo "FIRSTNUM=$(ruby -e 'puts rand(1..6)')" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
    - id: Print first num
      run: echo $FIRSTNUM
      shell: bash
