name: Yahtzee


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Roll-first-die:
    runs-on: [ linux, self-hosted, x64, rootless2 ]
    outputs:
      first_die: ${{ steps.Roll_dice.outputs.FIRSTROLL }}
    steps:
    - id: Roll_dice
      run: |
        FIRSTNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=FIRSTROLL::$FIRSTNUM
  Roll-second-die:
    runs-on: [ linux, self-hosted, x64, rootless2 ]
    outputs:
      second_die: ${{ steps.Roll_dice.outputs.SECONDROLL }}
    steps:
    - id: Roll_dice
      run: |
        SECONDNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=SECONDROLL::$SECONDNUM
  Roll-third-die:
    runs-on: [ linux, self-hosted, x64, rootless2 ]
    outputs:
      third_die: ${{ steps.Roll_dice.outputs.THIRDROLL }}
    steps:
    - id: Roll_dice
      run: |
        THIRDNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=THIRDROLL::$THIRDNUM
  Roll-fourth-die:
    runs-on: [ linux, self-hosted, x64, rootless2 ]
    outputs:
      fourth_die: ${{ steps.Roll_dice.outputs.FOURTHROLL }}
    steps:
    - id: Roll_dice
      run: |
        FOURTHNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=FOURTHROLL::$FOURTHNUM
  Roll-fifth-die:
    runs-on: [ linux, self-hosted, x64, rootless2 ]
    outputs:
      fifth_die: ${{ steps.Roll_dice.outputs.FIFTHROLL }}
    steps:
    - id: Roll_dice
      run: |
        FIFTHNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=FIFTHROLL::$FIFTHNUM
  Print-Roll:
    runs-on: [ linux, self-hosted, x64, rootless2 ]
    outputs:
      final_roll: ${{ steps.print-first-roll.outputs.final_roll }}
    needs: [ Roll-first-die,Roll-second-die,Roll-third-die,Roll-fourth-die,Roll-fifth-die ]
    steps:
    - uses: actions/checkout@v2
    - id: print-first-roll
      run: |
        echo First roll is ${{needs.Roll-first-die.outputs.first_die}}${{needs.Roll-second-die.outputs.second_die}}${{needs.Roll-third-die.outputs.third_die}}${{needs.Roll-fourth-die.outputs.fourth_die}}${{needs.Roll-fifth-die.outputs.fifth_die}}
        echo ::set-output name=final_roll::${{needs.Roll-first-die.outputs.first_die}}${{needs.Roll-second-die.outputs.second_die}}${{needs.Roll-third-die.outputs.third_die}}${{needs.Roll-fourth-die.outputs.fourth_die}}${{needs.Roll-fifth-die.outputs.fifth_die}}
    - uses: JasonEtco/create-an-issue@v2
      with:
        filename: .github/ISSUE_TEMPLATE/issue_from_action.md
      env:
        first_die: ${{needs.Roll-first-die.outputs.first_die}}
        second_die: ${{needs.Roll-second-die.outputs.second_die}}
        third_die: ${{needs.Roll-third-die.outputs.third_die}}
        fourth_die: ${{needs.Roll-fourth-die.outputs.fourth_die}}
        fifth_die: ${{needs.Roll-fifth-die.outputs.fifth_die}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Build-and-Push-Docker-Image:
    runs-on: [ linux, self-hosted, x64, rootless2 ]
    needs: [ Print-Roll ]
    name: Docker Build, Tag, Push
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run:
        echo Final roll is ${{needs.Print-Roll.outputs.final_roll}}
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: casanova-21/yahtzee/yahtzee
        tags: ${{needs.Print-Roll.outputs.final_roll}}
