name: Yahtzee

on:
  push:
    branches: [main]


jobs:
  Roll-dice:
    runs-on: ubuntu-latest
    outputs:
      first_die: ${{ steps.Roll_first_die.outputs.FIRSTROLL }}
    steps:
    - id: Roll_first_die
      run: |
        echo "FIRSTNUM=$(ruby -e 'puts rand(1..6)')" >> $GITHUB_ENV
        echo $FIRSTNUM
        echo hi
        echo ::set-output name=FIRSTROLL::$FIRSTNUM
      shell: bash
    - id: Print_first_num
      run: echo $FIRSTNUM
      shell: bash
    - id: Roll_second_die
      run: echo "SECONDNUM=$(ruby -e 'puts rand(1..6)')" >> $GITHUB_ENV
      shell: bash
    - id: Print_second_num
      run: echo $SECONDNUM
      shell: bash
    - id: Roll_third_die
      run: echo "THIRDNUM=$(ruby -e 'puts rand(1..6)')" >> $GITHUB_ENV
      shell: bash
    - id: Print_third_num
      run: echo $THIRDNUM
      shell: bash
    - id: Roll_fourth_die
      run: echo "FOURTHNUM=$(ruby -e 'puts rand(1..6)')" >> $GITHUB_ENV
      shell: bash
    - id: Print_fourth_num
      run: echo $FOURTHNUM
      shell: bash
    - id: Roll_fifth_die
      run: echo "FIFTHNUM=$(ruby -e 'puts rand(1..6)')" >> $GITHUB_ENV
      shell: bash
    - id: Print_fifth_num
      run: echo $FIFTHNUM
      shell: bash
    - id: Print_the_roll
      run: echo "$FIRSTNUM $SECONDNUM $THIRDNUM $FOURTHNUM $FIFTHNUM"
      shell: bash
  Print-Roll:
    runs-on: ubuntu-latest
    needs: Roll-dice
    steps:
    - id: print-final-roll
      run:
        echo Final roll is ${{needs.Roll-dice.outputs.first_die}}
