name: Yahtzee

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  Roll-dice:
    runs-on: ubuntu-latest
    outputs:
      first_die: ${{ steps.Roll_dice.outputs.FIRSTROLL }}
      second_die: ${{ steps.Roll_dice.outputs.SECONDROLL }}
      third_die: ${{ steps.Roll_dice.outputs.THIRDROLL }}
      fourth_die: ${{ steps.Roll_dice.outputs.FOURTHROLL }}
      fifth_die: ${{ steps.Roll_dice.outputs.FIFTHROLL }}
    steps:
    - id: Roll_dice
      run: |
        FIRSTNUM=$(ruby -e 'puts rand(1..6)')
        SECONDNUM=$(ruby -e 'puts rand(1..6)')
        THIRDNUM=$(ruby -e 'puts rand(1..6)')
        FOURTHNUM=$(ruby -e 'puts rand(1..6)')
        FIFTHNUM=$(ruby -e 'puts rand(1..6)')
        echo ::set-output name=FIRSTROLL::$FIRSTNUM
        echo ::set-output name=SECONDROLL::$SECONDNUM
        echo ::set-output name=THIRDROLL::$THIRDNUM
        echo ::set-output name=FOURTHROLL::$FOURTHNUM
        echo ::set-output name=FIFTHROLL::$FIFTHNUM
  Print-Roll:
    runs-on: ubuntu-latest
    needs: Roll-dice
    steps:
    - uses: actions/checkout@v2
    - id: print-final-roll
      run:
        echo Final roll is ${{needs.Roll-dice.outputs.first_die}}${{needs.Roll-dice.outputs.second_die}}${{needs.Roll-dice.outputs.third_die}}${{needs.Roll-dice.outputs.fourth_die}}${{needs.Roll-dice.outputs.fifth_die}}
    - uses: JasonEtco/create-an-issue@v2
      env: 
        first_die: ${{needs.Roll-dice.outputs.first_die}}
        second_die: ${{needs.Roll-dice.outputs.second_die}}
        third_die: ${{needs.Roll-dice.outputs.third_die}}
        fourth_die: ${{needs.Roll-dice.outputs.fourth_die}}
        fifth_die: ${{needs.Roll-dice.outputs.fifth_die}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
